"""Functional tests for the DMG bootstrap (launcher.sh) generated by build-dmg.sh.

The launcher is a bash heredoc inside build-dmg.sh, which only runs on macOS.
These tests render the heredoc exactly the way build-dmg.sh does (bash heredoc
expansion with LAUNCHER_ARCH set) and then execute the rendered script with a
sandbox HOME and PATH shims standing in for macOS-only commands (osascript,
uname, sysctl, xcode-select, ...). Dialogs are captured to a file so the tests
can assert what the user would actually SEE.

These flows are exactly the silent-death paths from the v0.3.2 field failure:
a launch that exits 0 with no visible UI and no menu bar icon.
"""
from __future__ import annotations

import os
import re
import subprocess
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
BUILD_SCRIPT = ROOT / "build-dmg.sh"

# The version the rendered test launcher is stamped with (BUNDLE_VERSION).
TEST_BUNDLE_VERSION = "9.9.9-test"


# ─────────────────────────────────────────────────────────────────────
# Rendering + sandbox harness
# ─────────────────────────────────────────────────────────────────────


def render_launcher() -> str:
    """Render launcher.sh from the build-dmg.sh heredoc, as a real build would."""
    text = BUILD_SCRIPT.read_text(encoding="utf-8")
    m = re.search(r'cat > "\$BOOTSTRAP" << LAUNCHER\n(.*?)\nLAUNCHER\n', text, re.S)
    assert m, "launcher heredoc not found in build-dmg.sh"
    body = m.group(1)
    # Reproduce heredoc expansion ($VAR expands, \$ stays literal) with the
    # same build-time variable build-dmg.sh sets.
    script = (
        f"LAUNCHER_ARCH=arm64\nLAUNCHER_VERSION={TEST_BUNDLE_VERSION}\n"
        "cat <<LAUNCHER\n" + body + "\nLAUNCHER\n"
    )
    rendered = subprocess.run(
        ["bash", "-c", script], capture_output=True, text=True, check=True,
    ).stdout
    # Neutralize the two hardcoded `eval "$(/opt/homebrew/bin/brew shellenv)"`
    # probes. On a real macOS runner those files exist and brew shellenv
    # re-prepends /opt/homebrew/bin ahead of our PATH shims — shadowing the
    # fake python3/brew/whisper and letting the launcher run real installs.
    # Pointing them at a nonexistent path keeps the shim PATH authoritative
    # on every platform; the brew-env import is not what these tests cover.
    rendered = rendered.replace("/opt/homebrew/bin/brew", "/nonexistent/ovf-test-brew")
    rendered = rendered.replace("/usr/local/bin/brew", "/nonexistent/ovf-test-brew")
    return rendered


def write_shim(bindir: Path, name: str, body: str) -> None:
    shim = bindir / name
    shim.write_text("#!/bin/bash\n" + body + "\n", encoding="utf-8")
    shim.chmod(0o755)


class LauncherSandbox:
    """Isolated HOME + shimmed PATH for one launcher run."""

    def __init__(self, tmp_path: Path):
        self.home = tmp_path / "home"
        self.home.mkdir()
        self.bin = tmp_path / "bin"
        self.bin.mkdir()
        self.dialogs = tmp_path / "dialogs.txt"
        self.launcher = tmp_path / "launcher.sh"
        self.launcher.write_text(render_launcher(), encoding="utf-8")
        self.launcher.chmod(0o755)

        # Default shims: a Mac-looking machine with a healthy toolchain.
        write_shim(self.bin, "uname", 'echo arm64')
        write_shim(self.bin, "sysctl", 'echo 0')
        write_shim(
            self.bin, "osascript",
            f'printf \'%s\\n\' "$*" >> "{self.dialogs}"',
        )
        write_shim(self.bin, "xcode-select", "exit 0")
        # whisper present by default so 'brew install' is skipped.
        write_shim(self.bin, "whisper-cli", "exit 0")
        write_shim(self.bin, "brew", "exit 0")

    def run(self, env_extra: dict | None = None, timeout: int = 60):
        env = dict(os.environ)
        env["HOME"] = str(self.home)
        env["PATH"] = f"{self.bin}:{env['PATH']}"
        env.update(env_extra or {})
        return subprocess.run(
            ["bash", str(self.launcher)],
            capture_output=True, text=True, env=env, timeout=timeout,
        )

    @property
    def log(self) -> str:
        log_file = self.home / "OpenVoiceFlow" / "launcher.log"
        return log_file.read_text(encoding="utf-8") if log_file.exists() else ""

    @property
    def shown_dialogs(self) -> str:
        return self.dialogs.read_text(encoding="utf-8") if self.dialogs.exists() else ""

    @property
    def state_dir(self) -> Path:
        return self.home / ".openvoiceflow"


@pytest.fixture
def sandbox(tmp_path):
    return LauncherSandbox(tmp_path)


# ─────────────────────────────────────────────────────────────────────
# Structural sanity
# ─────────────────────────────────────────────────────────────────────


def test_rendered_launcher_is_valid_bash(sandbox) -> None:
    check = subprocess.run(
        ["bash", "-n", str(sandbox.launcher)], capture_output=True, text=True,
    )
    assert check.returncode == 0, check.stderr


def test_smoke_mode_still_short_circuits(sandbox) -> None:
    result = sandbox.run(env_extra={"OVF_SMOKE_TEST": "1"})
    assert result.returncode == 0
    assert "launcher preflight passed" in sandbox.log


# ─────────────────────────────────────────────────────────────────────
# The silent-death regressions
# ─────────────────────────────────────────────────────────────────────


def test_stale_lock_from_reused_pid_is_cleared(sandbox) -> None:
    """Field failure: lock dir survives a reboot, its pid gets reused by an
    unrelated live process, and every launch exited silently forever."""
    lock_dir = sandbox.state_dir / ".bootstrap.lock"
    lock_dir.mkdir(parents=True)
    # pid 1 is alive on every unix but is definitely not launcher.sh
    (lock_dir / "pid").write_text("1", encoding="utf-8")

    # Make the run stop right after the lock step at the CLT probe, loudly.
    write_shim(sandbox.bin, "xcode-select", "exit 1")
    result = sandbox.run()

    assert "clearing stale bootstrap lock" in sandbox.log
    assert "already starting" not in sandbox.shown_dialogs
    # It proceeded past the lock and died at the (intentionally broken) CLT
    # gate — visibly, with a dialog and a non-zero exit.
    assert result.returncode == 1
    assert "Command Line Tools" in sandbox.shown_dialogs


def test_genuine_concurrent_launch_shows_dialog_and_exits_zero(sandbox, tmp_path) -> None:
    lock_dir = sandbox.state_dir / ".bootstrap.lock"
    lock_dir.mkdir(parents=True)

    # A live process whose command line contains launcher.sh, like a real
    # concurrent bootstrap would.
    holder = subprocess.Popen(
        ["bash", "-c", 'exec -a launcher.sh sleep 30'],
    )
    try:
        (lock_dir / "pid").write_text(str(holder.pid), encoding="utf-8")
        result = sandbox.run()
        assert result.returncode == 0
        assert "already starting" in sandbox.shown_dialogs
        assert "bootstrap already running" in sandbox.log
        # The genuine holder's lock must not be destroyed.
        assert lock_dir.exists()
    finally:
        holder.kill()
        holder.wait()


def test_missing_command_line_tools_fails_loudly(sandbox) -> None:
    """'command -v python3' always succeeds on macOS (Apple installer stub),
    so the launcher must probe xcode-select and fail with instructions."""
    write_shim(sandbox.bin, "xcode-select", '[[ "$1" == "-p" ]] && exit 1; exit 0')
    result = sandbox.run()
    assert result.returncode == 1
    assert "xcode-select --install" in sandbox.shown_dialogs


def test_broken_venv_is_detected_and_rebuilt(sandbox) -> None:
    """Field failure: a venv broken by a macOS/CLT update, with the deps
    marker present, skipped bootstrap and died silently every launch."""
    venv = sandbox.state_dir / "venv"
    (venv / "bin").mkdir(parents=True)
    write_shim(venv / "bin", "python3", "exit 1")  # broken interpreter
    (venv / ".ovf-deps-installed").write_text("", encoding="utf-8")

    # Fail venv recreation so the run stops right after the rebuild decision.
    write_shim(
        sandbox.bin, "python3",
        '[[ "$1" == "-m" && "$2" == "venv" ]] && exit 1; exit 0',
    )
    result = sandbox.run()

    assert "venv failed its health check - rebuilding" in sandbox.log
    assert not (venv / ".ovf-deps-installed").exists(), "broken venv must be wiped"
    assert result.returncode == 1
    assert "Could not create the Python environment" in sandbox.shown_dialogs


def test_first_run_announces_setup_before_the_silent_stretch(sandbox) -> None:
    """The user must be told what is happening BEFORE minutes of silence."""
    # Fresh HOME: no venv, no model → first-run work pending. Stop the run
    # at venv creation to keep the test hermetic (no pip/network).
    write_shim(
        sandbox.bin, "python3",
        '[[ "$1" == "-m" && "$2" == "venv" ]] && exit 1; exit 0',
    )
    result = sandbox.run()
    assert "First-time setup" in sandbox.shown_dialogs
    assert "menu bar" in sandbox.shown_dialogs
    assert result.returncode == 1  # stopped at the shimmed venv step, loudly


def test_repeat_launch_with_healthy_state_shows_no_setup_dialog(sandbox) -> None:
    """A healthy repeat launch must not nag: no first-run dialog, straight to
    the app. (Run is cut at the final PY_RUN exec via a python shim.)"""
    venv = sandbox.state_dir / "venv"
    (venv / "bin").mkdir(parents=True)
    # Health-check import probe and the site-packages query succeed; the
    # final big-script exec returns a sentinel so we know we reached it.
    write_shim(
        venv / "bin", "python3",
        'for a in "$@"; do\n'
        '  case "$a" in\n'
        '    *"import numpy"*) exit 0 ;;\n'
        '    *"import site"*) echo "' + str(venv / "lib") + '"; exit 0 ;;\n'
        '  esac\n'
        'done\n'
        'exit 42',
    )
    (venv / "lib").mkdir(exist_ok=True)
    write_shim(venv / "bin", "pip", "exit 0")
    # Marker must match the bundle version or the launcher reinstalls.
    (venv / ".ovf-deps-installed").write_text(TEST_BUNDLE_VERSION, encoding="utf-8")
    (sandbox.state_dir / "models").mkdir(parents=True, exist_ok=True)
    (sandbox.state_dir / "models" / "ggml-base.en.bin").write_text("x", encoding="utf-8")

    result = sandbox.run()
    assert "First-time setup" not in sandbox.shown_dialogs
    # The final stage ran the venv python (our stub's exit code proves it).
    assert result.returncode == 42


def test_upgrade_reinstalls_when_marker_version_differs(sandbox) -> None:
    """A venv from an OLDER app version must trigger a reinstall — otherwise
    a release that bumps a dependency breaks on import for upgraders."""
    venv = sandbox.state_dir / "venv"
    (venv / "bin").mkdir(parents=True)
    # Interpreter + native imports are healthy (so it's NOT the health-check
    # path); only the version stamp is stale.
    write_shim(venv / "bin", "python3", '[[ "$*" == *"import numpy"* ]] && exit 0; exit 0')
    (venv / ".ovf-deps-installed").write_text("0.0.1-old", encoding="utf-8")

    # Stop at the reinstall's venv/pip step so the test stays hermetic.
    write_shim(sandbox.bin, "python3", "exit 0")
    write_shim(
        sandbox.bin, "pip",
        'exit 1',  # pip --upgrade fails → fatal, run stops loudly
    )
    # pip is invoked as "$VENV/bin/pip"; shim that path too.
    write_shim(venv / "bin", "pip", "exit 1")

    result = sandbox.run()
    assert "reinstalling for" in sandbox.log
    # It went into the install branch (announced first-run work) rather than
    # launching straight through on the stale marker.
    assert "First-time setup" in sandbox.shown_dialogs
    assert result.returncode == 1
